name: Publish package version
on:
    push:
        tags:
            - version/*
jobs:
    publish_version:
        uses: DmitriyZverev/.github/.github/workflows/release.yml@v2.0.0-dev.3
        secrets:
            npm_token: ${{ secrets.NPM_TOKEN }}
