name: Check pull request
on:
    - pull_request
jobs:
    analize:
        uses: DmitriyZverev/.github/.github/workflows/analyze.yml@v2.0.0-dev.0
    build:
        uses: DmitriyZverev/.github/.github/workflows/build.yml@v2.0.0-dev.0
    test:
        uses: DmitriyZverev/.github/.github/workflows/test.yml@v2.0.0-dev.0
